export const datos = [
  // Saludos
  { id: 1, name: 'Hola', icon: ['/imagenes/HOLA.jpg'] },
  { id: 2, name: 'Chau', icon: ['/imagenes/CHAU.jpg'] },
  { id: 3, name: 'Permiso', icon: ['/imagenes/PERMISO.jpg'] },
  { id: 4, name: 'Buenos dias', icon: ['/imagenes/BUENOS_DIAS_A.jpg', '/imagenes/BUENOS_DIAS_B.jpg'] },
  { id: 5, name: 'Buenas tardes', icon: ['/imagenes/BUENAS_TARDES_A.jpg','/imagenes/BUENAS_TARDES_B.jpg'] },
  { id: 6, name: 'Gracias', icon: ['/imagenes/GRACIAS.jpg'] },
  { id: 7, name: 'Buenas noches', icon: ['/imagenes/BUENAS_NOCHES_A.jpg','/imagenes/BUENAS_NOCHES_B.jpg'] },
  { id: 8, name: 'Por favor', icon: ['/imagenes/POR_FAVOR.jpg'] },
  { id: 9, name: 'Como estas', icon: ['/imagenes/COMO_ESTAS_A.jpg','/imagenes/COMO_ESTAS_B.jpg'] },
  { id: 10, name: 'Estoy bien', icon: ['/imagenes/ESTOY_BIEN.jpg'] },
  { id: 11, name: 'Puedo', icon: ['/imagenes/PUEDO.jpg'] },
  { id: 12, name: 'No puedo', icon: ['/imagenes/NO_PUEDO.jpg'] },
  { id: 13, name: 'Mal', icon: ['/imagenes/MAL.jpg'] },
  { id: 14, name: 'Mas o menos', icon: ['/imagenes/MAS_O_MENOS.jpg'] },
  { id: 15, name: 'Nombre', icon: ['/imagenes/NOMBRE.jpg'] },
  { id: 16, name: 'Si', icon: ['/imagenes/SI.jpg'] },
  { id: 17, name: 'No', icon: ['/imagenes/NO.jpg'] },
  { id: 18, name: 'Lo siento', icon: ['/imagenes/LO_SIENTO.jpg'] },
  { id: 19, name: 'Te amo', icon: ['/imagenes/TE_AMO_A.jpg','/imagenes/TE_AMO_B.jpg'] },
];
